apiVersion: batch/v1
kind: Job
metadata:
  name: contract-deployer
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: contract-deployer
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: DOCKER_API_VERSION
              value: "1.45"
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: deploy-secrets
                  key: azureClientId
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: deploy-secrets
                  key: azureClientSecret
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: deploy-secrets
                  key: azureTenantId
            - name: DEPLOY_DOCKERIMAGE
              value: {{ .Values.deploy.dockerImage }}
            - name: DEPLOY_NETWORKNAME
              value: {{ .Values.deploy.networkName }}
            - name: DEPLOY_OUTPUTAZUREKV
              valueFrom:
                secretKeyRef:
                  name: deploy-secrets
                  key: azureKeyVaultUrl
            - name: DEPLOY_OUTPUTENV
              value: {{ .Values.deploy.outputEnv }}
            - name: DEPLOY_L1_RPCADDRESS
              valueFrom:
                secretKeyRef:
                  name: deploy-secrets
                  key: l1HttpUrl
            - name: DEPLOY_L1_DEPLOYERPK
              valueFrom:
                secretKeyRef:
                  name: deploy-secrets
                  key: deployerPrivateKey
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
      restartPolicy: Never