{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-deployer-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-deployer-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.serviceAccountName }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-deployer-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}