apiVersion: v1
kind: Secret
metadata:
  name: deploy-secrets
type: Opaque
stringData:
  azureClientId: {{ .Values.secrets.azureClientId | quote }}
  azureClientSecret: {{ .Values.secrets.azureClientSecret | quote }}
  azureTenantId: {{ .Values.secrets.azureTenantId | quote }}
  azureKeyVaultUrl: {{ .Values.secrets.azureKeyVaultUrl | quote }}
  l1HttpUrl: {{ .Values.secrets.l1HttpUrl | quote }}
  deployerPrivateKey: {{ .Values.secrets.deployerPrivateKey | quote }}
