{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ten-gateway.fullname" . }}-backend
  labels:
    {{- include "ten-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ten-gateway.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "ten-gateway.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      serviceAccountName: {{ include "ten-gateway.fullname" . }}-sa
      volumes:
        - name: shared-data
          emptyDir: {}
        - name: db-secret-volume
          secret:
            secretName: {{ include "ten-gateway.fullname" . }}-backend-secret
    
      containers:
        - name: {{ include "ten-gateway.name" . }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          command:
            - "/bin/bash"
            - "-c"
          args:
            - |
              set -a
              source /shared-data/env
              set +a
              ego run /home/ten/go-ten/tools/walletextension/main/main \
                -host=0.0.0.0 \
                -port=443 \
                -portWS=81 \
                -verbose=true \
                -logPath=sys_out \
                -dbType=cosmosDB \
                -dbConnectionURL="${dbConnectionURL}" \
                -rateLimitUserComputeTime=0 \
                -rateLimitWindow=1m \
                -maxConcurrentRequestsPerUser=5 \
                -keyExchangeURL="" \
                -insideEnclave=true \
                -enableTLS=true \
                -tlsDomain=rpc.dev-testnet.ten.xyz \
                -nodeHost=obscuronode-1-uat-testnet.uksouth.cloudapp.azure.com
          volumeMounts:
            - name: db-secret-volume
              mountPath: /secrets
              readOnly: true
          envFrom:
            - secretRef:
                name: {{ include "ten-gateway.fullname" . }}-backend-secret
  
  
          ports:
            - name: https
              containerPort: 443
            - name: ws
              containerPort: 444
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- end }}
