{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ten-gateway.fullname" . }}-frontend
  labels:
    {{- include "ten-gateway.labels" . | nindent 4 }}
    component: frontend
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ten-gateway.selectorLabels" . | nindent 4 }}
    component: frontend
{{- end }}