apiVersion: v1
kind: Service
metadata:
  name: {{ include "ten-gateway.fullname" . }}
  labels:
    {{- include "ten-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.wsPort }}
      targetPort: websocket
      protocol: TCP
      name: websocket
  selector:
    {{- include "ten-gateway.selectorLabels" . | nindent 4 }}
