image:
  repository: testnetobscuronet.azurecr.io/obscuronet/l1contractdeployer
  tag: 1.2.-beta
  pullPolicy: IfNotPresent

deploy:
  dockerImage: ""
  networkName: ""
  outputEnv: ""

secrets:
  azureClientId: ""
  azureClientSecret: ""
  azureTenantId: ""
  azureKeyVaultUrl: ""
  l1HttpUrl: ""
  deployerPrivateKey: ""

dind:
  resources:
    limits:
      cpu: 200m
      memory: 256Mi

resources:
  limits:
    cpu: 500m
    memory: 512Mi

backoffLimit: 1