# Default values for contract-deployer

deployer:
  image: golang:1.20
  gitRepo: https://github.com/ten-protocol/go-ten.git
  gitRef: main
  command: >
    cd /workspace &&
    go run ./testnet/launcher/l1contractdeployer/cmd
    -l1_http_url=${L1_HTTP_URL}
    -private_key=${PRIVATE_KEY}
    -output_file=/output/contracts.env

l1:
  httpUrl: ""  # Set via --set or secrets
  privateKey: "" # Set via --set or secrets

configmap:
  name: obscuro-contracts
  create: true

rbac:
  create: true
  serviceAccountName: contract-deployer-sa